user:
  name:
    maximum: 50
  email:
    maximum: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    minimum: 6
  movies: 2
movie:
  birthday: "%F"
  date: "%Y"
  day: "%F"
  title: 100
  slug: 100
  overview: 1000
  status_open: 1
  status_lock: 0
  inc_view_per: 1
comment: 2
search: 5
favorite: 5
enum_bookmark: 1
enum_favoriate: 0
zero: 0
twenty: 20
five: 5
